
# this will store the options when this cookiecutter was first built
default_context:
    project_name: "{{cookiecutter.project_slug}}",
    author_name: "{{cookiecutter.author_name}}",
    github_user: "{{cookiecutter.github_user}}",
    aim: "{{cookiecutter.aim}}",
    project_slug: "{{cookiecutter.project_slug}}",
    condaCacheDir: "{{cookiecutter.condaCacheDir}}"
